### ISSUE TITLE
Add 'Toggle All' button back into filter panel

### ISSUE THREAD

**Issue by judan** [texas-justice-initiative/website#9] opened 2018-06-25 21:08 UTC

**Comment by wetchler** [comment] 2018-06-26 04:36
@judan -- this seems like a duplicate of part of #3 -- can we mark this as a duplicate, and you assign yourself that issue? or did you have something else in mind here?

**Comment by judan** [comment] 2018-06-26 14:47
Yes, sorry didn't realize this had been incorporated into #3. I'll go ahead and close this. Thanks!

**Closed** 2018-06-27 17:46 UTC
